---
title: "Borealiis 3Di"
author: "PRU"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

# Top Borealis Aerodrome Pairs

Based on the NM flight table, we identify a set of top Borealis aerodrome pairs in Q1 and Q2 2023.

```{ nmflighttable, include=FALSE}
# for the selection of aerodrome pairs check stats with NM flight table
# uploaded Q1 & Q2 of NM flight table to data/NM-flt

pth    <- here::here("data","nm-flt")
fns_nm <- fs::dir_ls(path = pth)

nm_flt <- fns_nm %>% purrr::map_dfr(.f = ~ arrow::read_parquet(.x))

# Borealis members - pick 2 ICAO digits
# Denmark, Estonia, Finland, Iceland, Ireland, Latvia, Norway, Sweden and the UK.
bor_icao_2d <- c(
    "Denmark" = "EK", "Estonia" = "EE", "Finland" = "EF"
  , "Iceland" = "BI", "Ireland" = "EI", "Latvia"  = "EV"
  , "Norway"  = "EN", "Sweden"  = "ES", "UK" = "EG" )

# get departure, arrival, and internal flights := dai
bor_dai <- nm_flt %>% 
  filter( (substr(ADEP,1,2) %in% bor_icao_2d)|(substr(ADES,1,2) %in% bor_icao_2d) ) %>% 
  select(FLTID = AIRCRAFT_ID, REG = REGISTRATION, ICAO24 = AIRCRAFT_ADDRESS
         , ADEP, ADES
         , TYPE = AIRCRAFT_TYPE_ICAO_ID, WTC = WK_TBL_CAT
         , RFL  = FL_REQ, EET = FLT_DUR_3
         , EOBT = AOBT_3, ELDT = ARVT_3
         , ENTRY =IFPZ_ENTRY_TIME_ACT, EXIT = IFPZ_EXIT_TIME_ACT ) %>% 
  mutate(BOR_DAI = case_when(
        (substr(ADEP,1,2) %in% bor_icao_2d) & (substr(ADES,1,2) %in% bor_icao_2d) ~ "I"
      , (substr(ADEP,1,2) %in% bor_icao_2d) & !(substr(ADES,1,2) %in% bor_icao_2d)~ "D"
      , !(substr(ADEP,1,2) %in% bor_icao_2d)& (substr(ADES,1,2) %in% bor_icao_2d) ~ "A"
      )
  )

arrow::write_parquet(bor_dai, "./data/bor-dai-2023-Q1Q2.parquet")
```

```{r borealis_dai}
fns     <- fs::dir_ls(path = "./data", regexp = "bor-dai")
bor_dai <- fns %>% map_dfr(.f = ~ arrow::read_parquet(.x))

# helper function for aerodrome pair count
combo <- function(.adep, .ades){
    this_cp <- str_sort(c(.adep, .ades)) %>% paste(collapse = "-") 
}

# determine aerodrome pair connections
count_combos <- function(.combo_cons){
  .combo_cons %>% 
  rowwise() %>% mutate(CP = combo(ADEP, ADES)) %>% 
    mutate(
        OUTB = ifelse( glue::glue(ADEP,"-",ADES) == CP, N, 0)
      , BACK = ifelse( glue::glue(ADEP,"-",ADES) != CP, N, 0)
      , TOT = OUTB + BACK) %>% 
    group_by(CP) %>% 
    summarise(across(.cols = OUTB:BACK, .fns = sum)) %>% 
    mutate(TOT = OUTB + BACK) %>% arrange(desc(TOT))
}

rq <- bor_dai %>% filter(BOR_DAI == "I") %>% group_by(ADEP, ADES) %>% summarise(N = n(), .groups = "drop")

rq2 <- rq %>% rowwise() %>% mutate(CP = combo(ADEP, ADES)) %>% count_combos()
#write_csv(rq2, "./data/bor-cps-2023-Q1Q2.csv")
```

```{r}
bor_cnts <- read_csv("./data/bor-cps-2023-Q1Q2.csv", show_col_types = FALSE)

bor_cnts %>% slice_head(n = 20) %>% 
  mutate(CP = fct_reorder(CP, TOT)) %>% 
  ggplot() +
  geom_col(aes(x = TOT, y = CP))
```

Let's pick some arbitrary aerodrome pairs for the development

* EGLL-EIDW
* EKCH-ESSA
* EFHK-ESSA

```{r}
picks <- bor_dai %>% 
  rowwise() %>% mutate(ADP = combo(ADEP, ADES) ) %>% ungroup() %>% 
  filter(ADP %in% c("EGLL-EIDW","EKCH-ESSA","EFHK-ESSA"))
```

```{r}
picks %>% mutate(DOF = lubridate::floor_date(ELDT, unit = "day")) %>% group_by(ADP, DOF) %>% summarise(N = n(), .groups = "drop") %>% ggplot() + geom_path(aes(x = DOF, y = N, group = ADP)) + facet_wrap(. ~ADP)
```

arbitrary pick for study date: 2023-05-12 (Friday)

ahhhhhh dumps are gone .... stored in hive!


ok ... let's go with daily samples


```{r}
read_from_dailies <- function(.aerodrome_pair){
  tmp <- list.files(path = "./data/daily", pattern = .aerodrome_pair, full.names = TRUE)
  osn <- tmp %>% purrr::map_dfr(.f = ~ arrow::read_parquet(.x))
}
```

```{r}
egll_eidw <- read_from_dailies("EGLL_EIDW")
# too big: egll_eidw %>% arrow::write_parquet("EGLL_EIDW.parquet")
```


```{r}
(
whatsavailable <- tibble(FN = list.files(path = "./data/daily", full.names = TRUE)) %>% 
    mutate(
         ADP = str_extract(FN, pattern = "[A-Z]{4}_[A-Z]{4}")
        ,DOF = str_extract(FN, pattern = "\\_2023-[0-9]{2}-[0-9]{2}") %>% gsub(pattern = "_", replacement = ""))   
)
```

```{r}
get_svs_from_dailies <- function(.adp, .date_token, .available = whatsavailable) {
  svs <- .available %>% 
    filter(ADP %in% .adp, grepl(pattern = .date_token, x = DOF)) %>% 
    pull(FN) %>% purrr::map_dfr(.f = ~ arrow::read_parquet(.x) )
}

#get_svs_from_dailies("EGLL_EIDW", "2023-04") %>% arrow::write_parquet("./data/bor-dev-egll-eidw.parquet")
#get_svs_from_dailies("EKCH_ESSA", "2023-04") %>% arrow::write_parquet("./data/bor-dev-ekch-essa.parquet")
```

